global class SSPaymentModel {
    global String zTenantID{set;get;}
    global String zSignature{set;get;}
    global String zToken{set;get;}
    global String zKey{set;get;}
    global String zURL{set;get;}
    global String paymentType{set;get;}
    global String paymentPageId{set;get;} 
    global Boolean isDefault{set;get;}
    global String paymentGateway{set;get;}
    global String countryLanguage{set;get;}
    global String countryCurrency{set;get;}
    global String countryCode{set;get;}

}